const express=require('express');
const cookieParser=require('cookie-parser');
const {Pool}=require('pg');
const bcrypt=require('bcryptjs');
const crypto=require('crypto');
const path=require('path');
const app=express();
app.set('trust proxy',1);app.use(express.json({limit:'2mb'}));app.use(cookieParser());
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_SSL==='true'?{rejectUnauthorized:false}:undefined});
const q=(t,p=[])=>pool.query(t,p); const tokenHash=t=>crypto.createHash('sha256').update(t).digest('hex');
async function init(){
 await q(`CREATE EXTENSION IF NOT EXISTS pgcrypto;
 CREATE TABLE IF NOT EXISTS users(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),login text UNIQUE NOT NULL,name text NOT NULL,role text NOT NULL CHECK(role IN('student','teacher','admin')),password_hash text NOT NULL,status text NOT NULL DEFAULT 'active');
 CREATE TABLE IF NOT EXISTS sessions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),user_id uuid REFERENCES users(id) ON DELETE CASCADE,token_hash text UNIQUE NOT NULL,expires_at timestamptz NOT NULL,created_at timestamptz DEFAULT now());
 CREATE TABLE IF NOT EXISTS classes(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),name text NOT NULL,subject text NOT NULL,teacher_id uuid REFERENCES users(id),created_at timestamptz DEFAULT now());
 CREATE TABLE IF NOT EXISTS enrollments(class_id uuid REFERENCES classes(id) ON DELETE CASCADE,student_id uuid REFERENCES users(id) ON DELETE CASCADE,PRIMARY KEY(class_id,student_id));
 CREATE TABLE IF NOT EXISTS exams(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),title text NOT NULL,subject text NOT NULL,duration int NOT NULL DEFAULT 45,max_score numeric NOT NULL DEFAULT 10,questions jsonb NOT NULL,owner_id uuid REFERENCES users(id),status text NOT NULL DEFAULT 'published',created_at timestamptz DEFAULT now());
 CREATE TABLE IF NOT EXISTS assignments(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),exam_id uuid REFERENCES exams(id),class_id uuid REFERENCES classes(id),title text NOT NULL,open_at timestamptz NOT NULL,close_at timestamptz NOT NULL,duration int NOT NULL,max_attempts int NOT NULL DEFAULT 1,created_at timestamptz DEFAULT now());
 CREATE TABLE IF NOT EXISTS attempts(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),assignment_id uuid REFERENCES assignments(id),student_id uuid REFERENCES users(id),started_at timestamptz DEFAULT now(),deadline_at timestamptz NOT NULL,status text NOT NULL DEFAULT 'in_progress',answers jsonb NOT NULL DEFAULT '{}'::jsonb,score numeric,submitted_at timestamptz,manual_comment text,UNIQUE(assignment_id,student_id));
 CREATE TABLE IF NOT EXISTS audit(id bigserial PRIMARY KEY,user_id uuid,action text NOT NULL,meta jsonb,created_at timestamptz DEFAULT now());`);
 if(process.env.SEED_ON_BOOT==='true') await seed();
}
async function upsertUser(login,name,role,password){const hash=await bcrypt.hash(password,12);return (await q(`INSERT INTO users(login,name,role,password_hash) VALUES($1,$2,$3,$4) ON CONFLICT(login) DO UPDATE SET name=excluded.name,role=excluded.role,password_hash=excluded.password_hash RETURNING *`,[login,name,role,hash])).rows[0]}
async function seed(){
 const teacher=await upsertUser('gv','Giáo viên Vinh','teacher',process.env.SEED_TEACHER_PASSWORD||'ChangeMe!');
 const student=await upsertUser('hs','Học sinh VINH EXAM','student',process.env.SEED_STUDENT_PASSWORD||'ChangeMe!');
 await upsertUser('qt','Quản trị VINH EXAM','admin',process.env.SEED_ADMIN_PASSWORD||'ChangeMe!');
 let c=(await q(`SELECT * FROM classes WHERE name='11A1 – Vật lí' LIMIT 1`)).rows[0]; if(!c)c=(await q(`INSERT INTO classes(name,subject,teacher_id) VALUES('11A1 – Vật lí','Vật lí 11',$1) RETURNING *`,[teacher.id])).rows[0];
 await q(`INSERT INTO enrollments(class_id,student_id) VALUES($1,$2) ON CONFLICT DO NOTHING`,[c.id,student.id]);
 let e=(await q(`SELECT * FROM exams WHERE title='Đề mẫu Vật lí 11 – Dao động' LIMIT 1`)).rows[0];
 if(!e){const questions=[
 {id:'q1',type:'single',text:'Trong dao động điều hòa, khi vật đi qua vị trí cân bằng thì đại lượng nào đạt độ lớn cực đại?',options:['Li độ','Vận tốc','Gia tốc','Thế năng'],answer:1,points:2,explanation:'Tại vị trí cân bằng, vận tốc đạt độ lớn cực đại.'},
 {id:'q2',type:'tf',text:'Xác định Đúng/Sai',statements:['Gia tốc luôn hướng về vị trí cân bằng.','Vận tốc luôn cùng chiều với gia tốc.','Ở biên, vận tốc bằng 0.','Ở vị trí cân bằng, gia tốc bằng 0.'],answer:[true,false,true,true],points:3},
 {id:'q3',type:'number',text:'Một vật có chu kì T = 0,50 s. Tần số f bằng bao nhiêu Hz?',answer:2,tolerance:.01,points:2},
 {id:'q4',type:'essay',text:'Giải thích vì sao khi lực cản tăng thì dao động tắt dần nhanh hơn.',points:3}
 ];e=(await q(`INSERT INTO exams(title,subject,duration,max_score,questions,owner_id) VALUES($1,$2,45,10,$3,$4) RETURNING *`,['Đề mẫu Vật lí 11 – Dao động','Vật lí 11',JSON.stringify(questions),teacher.id])).rows[0]}
 let a=(await q(`SELECT * FROM assignments WHERE title='Bài thi demo — Dao động' LIMIT 1`)).rows[0]; if(!a) await q(`INSERT INTO assignments(exam_id,class_id,title,open_at,close_at,duration) VALUES($1,$2,$3,now()-interval '1 hour',now()+interval '30 days',45)`,[e.id,c.id,'Bài thi demo — Dao động']);
 console.log('Seeded VINH EXAM');
}
async function auth(req,res,next){const raw=req.cookies.vx_session;if(!raw)return res.status(401).json({message:'Chưa đăng nhập'});const r=await q(`SELECT u.*,s.id session_id FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=$1 AND s.expires_at>now() AND u.status='active'`,[tokenHash(raw)]);if(!r.rowCount)return res.status(401).json({message:'Phiên đăng nhập đã hết hạn'});req.user=r.rows[0];next()}
const role=(...rs)=>(req,res,next)=>rs.includes(req.user.role)?next():res.status(403).json({message:'Không có quyền'});
app.post('/api/auth/login',async(req,res)=>{const login=String(req.body.login||'').trim().toLowerCase(),password=String(req.body.password||'');const r=await q(`SELECT * FROM users WHERE login=$1 AND status='active'`,[login]);if(!r.rowCount||!await bcrypt.compare(password,r.rows[0].password_hash))return res.status(401).json({message:'Tên đăng nhập hoặc mật khẩu không đúng'});const raw=crypto.randomBytes(32).toString('base64url'),exp=new Date(Date.now()+7*864e5);await q(`INSERT INTO sessions(user_id,token_hash,expires_at) VALUES($1,$2,$3)`,[r.rows[0].id,tokenHash(raw),exp]);res.cookie('vx_session',raw,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',expires:exp,path:'/'});res.json({user:{id:r.rows[0].id,name:r.rows[0].name,login:r.rows[0].login,role:r.rows[0].role}})});
app.get('/api/auth/me',auth,(req,res)=>res.json({user:{id:req.user.id,name:req.user.name,login:req.user.login,role:req.user.role}}));
app.post('/api/auth/logout',auth,async(req,res)=>{await q(`DELETE FROM sessions WHERE id=$1`,[req.user.session_id]);res.clearCookie('vx_session',{path:'/'});res.json({ok:true})});
app.get('/api/student/dashboard',auth,role('student'),async(req,res)=>{const r=await q(`SELECT a.id assignment_id,a.title,a.open_at,a.close_at,a.duration,e.title exam_title,c.name class_name,at.id attempt_id,at.status,at.score FROM enrollments en JOIN classes c ON c.id=en.class_id JOIN assignments a ON a.class_id=c.id JOIN exams e ON e.id=a.exam_id LEFT JOIN attempts at ON at.assignment_id=a.id AND at.student_id=$1 WHERE en.student_id=$1 ORDER BY a.open_at DESC`,[req.user.id]);res.json({assignments:r.rows})});
app.post('/api/student/start/:id',auth,role('student'),async(req,res)=>{const a=(await q(`SELECT a.* FROM assignments a JOIN enrollments en ON en.class_id=a.class_id WHERE a.id=$1 AND en.student_id=$2 AND now() BETWEEN a.open_at AND a.close_at`,[req.params.id,req.user.id])).rows[0];if(!a)return res.status(400).json({message:'Bài thi chưa mở, đã đóng hoặc không thuộc lớp của bạn'});let at=(await q(`SELECT * FROM attempts WHERE assignment_id=$1 AND student_id=$2`,[a.id,req.user.id])).rows[0];if(!at)at=(await q(`INSERT INTO attempts(assignment_id,student_id,deadline_at) VALUES($1,$2,LEAST(now()+($3||' minutes')::interval,$4)) RETURNING *`,[a.id,req.user.id,a.duration,a.close_at])).rows[0];res.json({attemptId:at.id})});
app.get('/api/student/attempt/:id',auth,role('student'),async(req,res)=>{const r=await q(`SELECT at.*,a.title,a.duration,e.title exam_title,e.questions FROM attempts at JOIN assignments a ON a.id=at.assignment_id JOIN exams e ON e.id=a.exam_id WHERE at.id=$1 AND at.student_id=$2`,[req.params.id,req.user.id]);if(!r.rowCount)return res.status(404).json({message:'Không tìm thấy lượt thi'});const x=r.rows[0];const questions=x.questions.map(({answer,explanation,tolerance,...safe})=>safe);res.json({attempt:{id:x.id,status:x.status,deadlineAt:x.deadline_at,answers:x.answers,score:x.score,title:x.title,examTitle:x.exam_title,questions}})});
app.post('/api/student/attempt/:id/save',auth,role('student'),async(req,res)=>{const r=await q(`UPDATE attempts SET answers=$1 WHERE id=$2 AND student_id=$3 AND status='in_progress' AND deadline_at>now() RETURNING id`,[JSON.stringify(req.body.answers||{}),req.params.id,req.user.id]);if(!r.rowCount)return res.status(409).json({message:'Không thể lưu: bài đã nộp hoặc hết giờ'});res.json({savedAt:new Date().toISOString()})});
function gradeQuestions(qs,answers){let score=0,pending=false;for(const x of qs){const a=answers[x.id];if(x.type==='single'&&Number(a)===x.answer)score+=Number(x.points);else if(x.type==='tf'&&Array.isArray(a)){const n=x.answer.filter((v,i)=>a[i]===v).length;score+=Number(x.points)*([0,.1,.25,.5,1][n]||0)}else if(x.type==='number'&&Math.abs(Number(a)-Number(x.answer))<=Number(x.tolerance||0))score+=Number(x.points);else if(x.type==='essay')pending=true}return {score:+score.toFixed(2),pending}}
app.post('/api/student/attempt/:id/submit',auth,role('student'),async(req,res)=>{const r=await q(`SELECT at.*,e.questions FROM attempts at JOIN assignments a ON a.id=at.assignment_id JOIN exams e ON e.id=a.exam_id WHERE at.id=$1 AND at.student_id=$2`,[req.params.id,req.user.id]);if(!r.rowCount)return res.status(404).json({message:'Không tìm thấy lượt thi'});const at=r.rows[0];if(at.status!=='in_progress')return res.json({ok:true,status:at.status});const g=gradeQuestions(at.questions,at.answers||{});await q(`UPDATE attempts SET status=$1,score=$2,submitted_at=now() WHERE id=$3`,[g.pending?'pending_manual':'graded',g.score,at.id]);res.json({ok:true,status:g.pending?'pending_manual':'graded',score:g.pending?null:g.score})});
app.get('/api/student/result/:id',auth,role('student'),async(req,res)=>{const r=await q(`SELECT at.id,at.status,at.score,at.submitted_at,at.manual_comment,a.title,e.title exam_title FROM attempts at JOIN assignments a ON a.id=at.assignment_id JOIN exams e ON e.id=a.exam_id WHERE at.id=$1 AND at.student_id=$2`,[req.params.id,req.user.id]);if(!r.rowCount)return res.status(404).json({message:'Không tìm thấy kết quả'});res.json({result:r.rows[0]})});
app.get('/api/teacher/dashboard',auth,role('teacher'),async(req,res)=>{const [c,e,p]=await Promise.all([q(`SELECT count(*)::int n FROM classes WHERE teacher_id=$1`,[req.user.id]),q(`SELECT count(*)::int n FROM exams WHERE owner_id=$1`,[req.user.id]),q(`SELECT count(*)::int n FROM attempts at JOIN assignments a ON a.id=at.assignment_id JOIN classes c ON c.id=a.class_id WHERE c.teacher_id=$1 AND at.status='pending_manual'`,[req.user.id])]);res.json({stats:{classes:c.rows[0].n,exams:e.rows[0].n,pending:p.rows[0].n}})});
app.get('/api/teacher/classes',auth,role('teacher'),async(req,res)=>res.json({classes:(await q(`SELECT c.*,count(en.student_id)::int students FROM classes c LEFT JOIN enrollments en ON en.class_id=c.id WHERE c.teacher_id=$1 GROUP BY c.id ORDER BY c.created_at DESC`,[req.user.id])).rows}));
app.post('/api/teacher/classes',auth,role('teacher'),async(req,res)=>{const r=await q(`INSERT INTO classes(name,subject,teacher_id) VALUES($1,$2,$3) RETURNING *`,[req.body.name,req.body.subject||'',req.user.id]);res.json({class:r.rows[0]})});
app.get('/api/teacher/exams',auth,role('teacher'),async(req,res)=>res.json({exams:(await q(`SELECT id,title,subject,duration,max_score,status,created_at FROM exams WHERE owner_id=$1 ORDER BY created_at DESC`,[req.user.id])).rows}));
app.post('/api/teacher/exams',auth,role('teacher'),async(req,res)=>{const questions=Array.isArray(req.body.questions)?req.body.questions:[];const r=await q(`INSERT INTO exams(title,subject,duration,max_score,questions,owner_id) VALUES($1,$2,$3,$4,$5,$6) RETURNING id,title`,[req.body.title,req.body.subject||'',Number(req.body.duration||45),Number(req.body.maxScore||10),JSON.stringify(questions),req.user.id]);res.json({exam:r.rows[0]})});
app.get('/api/teacher/assignments',auth,role('teacher'),async(req,res)=>res.json({assignments:(await q(`SELECT a.*,e.title exam_title,c.name class_name,(SELECT count(*) FROM attempts at WHERE at.assignment_id=a.id)::int attempts FROM assignments a JOIN exams e ON e.id=a.exam_id JOIN classes c ON c.id=a.class_id WHERE c.teacher_id=$1 ORDER BY a.created_at DESC`,[req.user.id])).rows}));
app.post('/api/teacher/assignments',auth,role('teacher'),async(req,res)=>{const c=await q(`SELECT 1 FROM classes WHERE id=$1 AND teacher_id=$2`,[req.body.classId,req.user.id]);const e=await q(`SELECT duration FROM exams WHERE id=$1 AND owner_id=$2`,[req.body.examId,req.user.id]);if(!c.rowCount||!e.rowCount)return res.status(403).json({message:'Không có quyền với lớp hoặc đề'});const open=new Date(req.body.openAt||Date.now()),close=new Date(req.body.closeAt||Date.now()+7*864e5);const r=await q(`INSERT INTO assignments(exam_id,class_id,title,open_at,close_at,duration) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[req.body.examId,req.body.classId,req.body.title||'Bài kiểm tra',open,close,Number(req.body.duration||e.rows[0].duration)]);res.json({assignment:r.rows[0]})});
app.get('/api/teacher/monitor/:id',auth,role('teacher'),async(req,res)=>{const own=await q(`SELECT 1 FROM assignments a JOIN classes c ON c.id=a.class_id WHERE a.id=$1 AND c.teacher_id=$2`,[req.params.id,req.user.id]);if(!own.rowCount)return res.status(403).json({message:'Không có quyền'});const rows=(await q(`SELECT u.name,at.id,at.status,at.started_at,at.deadline_at,at.score,jsonb_object_length(COALESCE(at.answers,'{}'::jsonb)) answered FROM attempts at JOIN users u ON u.id=at.student_id WHERE at.assignment_id=$1 ORDER BY at.started_at`,[req.params.id])).rows;res.json({attempts:rows})});
app.get('/api/teacher/pending',auth,role('teacher'),async(req,res)=>res.json({attempts:(await q(`SELECT at.id,u.name,a.title,at.score FROM attempts at JOIN users u ON u.id=at.student_id JOIN assignments a ON a.id=at.assignment_id JOIN classes c ON c.id=a.class_id WHERE c.teacher_id=$1 AND at.status='pending_manual'`,[req.user.id])).rows}));
app.post('/api/teacher/grade/:id',auth,role('teacher'),async(req,res)=>{const r=await q(`SELECT at.id,at.score,e.questions FROM attempts at JOIN assignments a ON a.id=at.assignment_id JOIN classes c ON c.id=a.class_id JOIN exams e ON e.id=a.exam_id WHERE at.id=$1 AND c.teacher_id=$2 AND at.status='pending_manual'`,[req.params.id,req.user.id]);if(!r.rowCount)return res.status(404).json({message:'Không tìm thấy bài chờ chấm'});const maxEssay=r.rows[0].questions.filter(x=>x.type==='essay').reduce((s,x)=>s+Number(x.points),0);const manual=Math.max(0,Math.min(maxEssay,Number(req.body.points||0))),total=Number(r.rows[0].score||0)+manual;await q(`UPDATE attempts SET score=$1,status='graded',manual_comment=$2 WHERE id=$3`,[total,String(req.body.comment||''),req.params.id]);res.json({ok:true,score:total})});
app.get('/api/admin/dashboard',auth,role('admin'),async(req,res)=>{const u=(await q(`SELECT role,count(*)::int n FROM users GROUP BY role`)).rows;const c=(await q(`SELECT count(*)::int n FROM classes`)).rows[0].n,e=(await q(`SELECT count(*)::int n FROM exams`)).rows[0].n,a=(await q(`SELECT count(*)::int n FROM attempts`)).rows[0].n;res.json({users:u,classes:c,exams:e,attempts:a})});
app.get('/api/admin/users',auth,role('admin'),async(req,res)=>res.json({users:(await q(`SELECT id,login,name,role,status FROM users ORDER BY role,name`)).rows}));
app.get('/api/health',(req,res)=>res.json({ok:true,service:'vinh-exam',time:new Date().toISOString()}));
app.use(express.static(path.join(__dirname,'public')));app.get('*',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));
const port=Number(process.env.PORT||3000);init().then(()=>app.listen(port,'0.0.0.0',()=>console.log(`VINH EXAM running on ${port}`))).catch(e=>{console.error(e);process.exit(1)});
