const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {JSDOM}=require('jsdom');
const build=require('../scripts/build-client');
const response=data=>({ok:true,status:200,json:async()=>data});
const tick=()=>new Promise(r=>setImmediate(r));
const model={kind:'harmonic',caption:'Li độ theo thời gian',xLabel:'t (s)',yLabel:'x (cm)',xMin:0,xMax:4,yMin:-3,yMax:3,amplitude:2,period:2,phase:0,timeEnd:4};
const solution={status:'ready',knowledge:['Dao động điều hòa'],steps:[{title:'Tính li độ',text:'Thay thời điểm vào phương trình.',formula:'\\(x=2\\cos(\\pi t)\\)'}],conclusion:'Li độ bằng 2 cm.',commonMistake:'Pha tính bằng radian.',visual:model};
function client(handler){const files=build(),root=path.join(__dirname,'..','public');const dom=new JSDOM(fs.readFileSync(path.join(root,'index.html'),'utf8'),{url:'https://exam.test',runScripts:'outside-only',pretendToBeVisual:true});const w=dom.window;w.fetch=async(url,opt)=>url==='/api/auth/me'?{ok:false,status:401,json:async()=>({})}:response(await handler(url,opt));w.matchMedia=()=>({matches:true,addEventListener(){}});w.EventSource=class{close(){}};w.Element.prototype.animate=()=>({finished:Promise.resolve(),cancel(){}});w.eval(fs.readFileSync(path.join(root,'dist',files.js),'utf8'));return dom;}
test('teacher sees the actual connection problem and progress counts successful solutions only',async()=>{
 const job={status:'blocked',done:18,total:22,ready:0,errors:0,needsReview:0,remaining:22,issue:{code:'AI_QUOTA',message:'OpenAI API báo không đủ hạn mức. Kiểm tra Billing.',automatic:false},items:[{position:0,status:'blocked',reason:'Không đủ hạn mức',question:{text:'<script>Question</script>'}}]};
 const dom=client(async()=>({assignment:{id:'as',title:'Đề',aiEnabled:true},context:{grade:10},counts:{graded:1,pending:0},aiConfigured:true,job}));
 try{await tick();await dom.window.openResultRelease('as');const d=dom.window.document;assert.match(d.querySelector('.ai-provider-alert').textContent,/không đủ hạn mức/);assert.match(d.querySelector('.ai-progress-line').textContent,/0\/22 câu có lời giải/);assert.equal(d.querySelector('progress').value,0);assert.match(d.querySelector('.ai-preview').textContent,/Kiểm tra & thử lại/);assert.equal(d.querySelector('.ai-job-item script'),null);
  job.issue=null;job.status='failed';job.items[0].status='error';await dom.window.openResultRelease('as');assert.equal(d.querySelector('.ai-job-item').open,true);assert.match(d.querySelector('.ai-review-reason').textContent,/Không đủ hạn mức/);
 }finally{dom.window.close();}
});
test('teacher can grade and choose publication without setting any simulation parameters',async()=>{
 const release={assignment:{id:'as',title:'Đề Lý',showScore:false,showAnswers:false,showExplanations:false,aiEnabled:false},context:{grade:11,subject:'Vật lí',lesson:'Dao động',scope:''},aiConfigured:false,counts:{graded:1,pending:0},job:null};let saved;
 const dom=client(async(url,opt)=>{if(url==='/api/teacher/attempts/a/grading')return {attempt:{id:'a',student_name:'HS',exam_title:'Đề',questions:[{id:'q',type:'essay',text:'Giải thích',points:2}],answers:{q:'Bài làm'}},objectiveScore:3,maxManual:2,manualPoints:0,release};if(url==='/api/teacher/attempts/a/grade-and-release'){saved=JSON.parse(opt.body);return {score:4,assignmentId:'as'};}if(url==='/api/teacher/pending')return {attempts:[]};if(url==='/api/teacher/assignments/as/release')return release;throw Error('Unexpected '+url);});
 try{await tick();const w=dom.window,d=w.document;w.eval("ME={role:'teacher',name:'GV'}");await w.openGrade('a');d.querySelector('#releaseAI').checked=true;w.syncReleaseChoices(true);assert.equal(d.querySelector('#releaseAnswers').checked,true);assert.equal(d.querySelector('#releaseAIContext').hidden,false);assert.equal(d.querySelector('#aiGrade').value,'11');assert.match(d.querySelector('.ai-connection-note').textContent,/chưa kết nối/);assert.equal(d.querySelector('[data-sim-param]'),null);d.querySelector('#manualPoints').value='1';await w.saveGrade('a',true);assert.equal(saved.points,1);assert.equal(saved.publication.ai,true);assert.equal(saved.publication.context.grade,11);assert.ok(d.querySelector('#releaseSaveButton'));}finally{dom.window.close()}
});
test('student sees detailed steps and matching interactive model only when explanations are published',async()=>{
 let published=true,saves=0;const dom=client(async(url,opt)=>{if(url==='/api/student/result/a/published')return {result:{id:'a',title:'Bài kiểm tra',exam_title:'Dao động',status:'graded',score:8,max_score:10,submitted_at:new Date().toISOString()},policy:{showScore:true,showAnswers:true,showExplanations:published},review:{answers:{q:0},questions:[{id:'q',type:'single',text:'Tính li độ',options:['2','0'],answer:0,aiSolution:solution}],ai:{ready:1,total:1,pending:false}}};if(url.endsWith('/save'))saves++;throw Error('Unexpected '+url);});
 try{await tick();const w=dom.window,d=w.document;w.eval("ME={role:'student',name:'HS'}");await w.showResult('a');assert.ok(d.querySelector('.ai-solution'));assert.match(d.querySelector('.ai-steps').textContent,/Thay thời điểm/);const root=d.querySelector('.ai-visual'),before=root.querySelector('circle').getAttribute('cy'),slider=root.querySelector('[data-ai-time]');slider.value='1';slider.dispatchEvent(new w.Event('input',{bubbles:true}));assert.notEqual(root.querySelector('circle').getAttribute('cy'),before);assert.equal(saves,0);root.querySelector('[data-ai-play]').click();assert.match(d.querySelector('#toast').textContent,/giảm chuyển động/);published=false;await w.showResult('a');assert.equal(d.querySelector('.ai-solution'),null);assert.equal(d.querySelector('.ai-visual'),null);}finally{dom.window.close()}
});
