const {test}=require('node:test');
const assert=require('node:assert/strict');
const Module=require('node:module');
const path=require('node:path');
const {PGlite}=require('@electric-sql/pglite');
const P=require('../lib/prepared-solutions');
const {createService}=require('../lib/ai-solutions');
const motion={kind:'motion',caption:'Tọa độ theo thời gian',xLabel:'t (s)',yLabel:'x (m)',xMin:0,xMax:4,yMin:0,yMax:20,timeEnd:4,bodies:[{label:'Vật',x0:0,v0:2,acceleration:1}]};
const solution={status:'ready',reason:'',knowledge:['Chuyển động thẳng biến đổi đều'],steps:[{title:'Tính tọa độ',text:'Chọn gốc tọa độ tại vị trí ban đầu. Với t = 4 s, thay số vào phương trình chuyển động.',formula:'\\[x=2\\cdot4+\\frac12\\cdot1\\cdot4^2=16\\text{ m}\\]'}],conclusion:'Vật ở tọa độ 16 m.',commonMistake:'Không bỏ hệ số một phần hai.',answer:16,visual:motion};
const questions=[{id:'motion-q',type:'number',text:'Vật xuất phát từ O, vận tốc 2 m/s, gia tốc 1 m/s². Tọa độ sau 4 s?',answer:16,tolerance:0,points:7},{id:'essay-q',type:'essay',text:'Giải thích vì sao tọa độ tăng nhanh dần.',points:3}];
const fixture={id:'assignment-1',title:'Chuyển động lớp 10',subject:'Vật lí 10',questions};
function pack(a=fixture){const p=P.template(a);p.items[0].solution=structuredClone(solution);return p;}
test('bulk solutions match stable ids, check answer keys, merge partial input and reject ambiguous or unsafe files',()=>{
 const p=pack(),out=P.prepare(fixture,JSON.stringify(p));assert.equal(out.ready,1);assert.equal(out.visuals,1);assert.equal(out.preview[0].answerChecked,true);assert.deepEqual(out.missing,[2]);assert.equal(out.items[0].solution.source,'prepared');
 assert.equal(P.prepare(fixture,'```json\n'+JSON.stringify(p)+'\n```').previewToken,out.previewToken);
 assert.throws(()=>P.prepare(fixture,JSON.stringify(P.template(fixture))),/chưa có lời giải/);
 const a={...fixture,prepared_solution_id:'first-version'},existing={fingerprint:out.fingerprint,items:out.items};
 const text=P.prepare(a,'Câu 2.\nVận tốc tăng đều nên độ dốc đồ thị tọa độ tăng.\nKết luận: Tọa độ tăng nhanh dần.',existing);assert.equal(text.ready,2);assert.equal(text.retained,1);assert.equal(text.preview[0].number,2);assert.equal(text.preview[0].answerChecked,false);
 const replace=P.prepare(a,'Câu 1.\nThay t = 4 vào x = 2t + 0,5t².\nKết luận: x = 16 m.',existing);assert.equal(replace.replaced,1);assert.ok(replace.warnings.some(x=>x.includes('đối chiếu tự động')));
 assert.throws(()=>P.prepare(fixture,'Câu 1.\nA\nCâu 1.\nB'),/bị lặp/);
 assert.throws(()=>P.prepare(fixture,'Câu 3.\nA'),/số câu hợp lệ/);
 assert.throws(()=>P.prepare(fixture,'Tiêu đề\nCâu 1.\nA'),/bắt đầu/);
 assert.throws(()=>P.prepare(fixture,'x'.repeat(P.MAX_BYTES+1)),/1 MB/);
 const bad=structuredClone(p);bad.assignmentId='other';assert.throws(()=>P.prepare(fixture,JSON.stringify(bad)),/bài giao khác/);
 bad.assignmentId=fixture.id;bad.items[0].number=2;assert.throws(()=>P.prepare(fixture,JSON.stringify(bad)),/không khớp/);
 bad.items[0].number=1;bad.items[0].solution.answer=15;assert.throws(()=>P.prepare(fixture,JSON.stringify(bad)),/không khớp đáp án/);
 bad.items[0].solution.answer=16;bad.items[0].solution.visual={kind:'javascript',code:'alert(1)'};assert.throws(()=>P.prepare(fixture,JSON.stringify(bad)),/Câu 1/);
 bad.items[0].solution=solution;bad.items[0].question.text='Câu khác';assert.throws(()=>P.prepare(fixture,JSON.stringify(bad)),/không khớp đề/);
 assert.throws(()=>P.prepare({...fixture,questions:[{...questions[0],text:'Đã đổi'},questions[1]]},JSON.stringify(p)),e=>e.status===409);
});
test('stored solutions persist without API calls and respect ownership, grading, timing, revocation and shuffled questions',{timeout:120000},async t=>{
 const db=new PGlite();
 const query=async(sql,params=[])=>{sql=sql.replace('CREATE EXTENSION IF NOT EXISTS pgcrypto;','');const r=params.length?await db.query(sql,params):(await db.exec(sql)).at(-1);return {...r,rowCount:Math.max(r?.affectedRows||0,r?.rows?.length||0)};};
 const pool={query,connect:async()=>({query,release(){}})};let calls=0;
 const provider={configured:()=>false,model:()=> 'unused',generate:async()=>{calls++;throw Error('Must not call AI');}};
 const code=require('../server-hotfix').code,filename=path.join(__dirname,'..','server-v2.js'),mod=new Module(filename,module);mod.filename=filename;mod.paths=Module._nodeModulePaths(path.dirname(filename));const normal=mod.require.bind(mod);
 mod.require=name=>name==='pg'?{Pool:function(){return pool}}:name==='./lib/ai-solutions'?{createService:opts=>{const service=createService({...opts,provider,env:{AI_SOLUTIONS_DISABLED:'true'}});service.pump=async()=>{};return service;}}:normal(name);
 mod._compile(code.slice(0,code.indexOf('const port = Number(process.env.PORT'))+'\nmodule.exports={app,migrate,aiSolutions};',filename);await mod.exports.migrate();
 const server=mod.exports.app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));t.after(async()=>{await new Promise(r=>server.close(r));await db.close();});
 const base='http://127.0.0.1:'+server.address().port+'/api';
 async function api(url,{body,cookie,method=body?'POST':'GET',status=200}={}){const r=await fetch(base+url,{method,headers:{'Content-Type':'application/json',...(cookie?{Cookie:cookie}:{})},...(body?{body:JSON.stringify(body)}:{})});const data=await r.json();assert.equal(r.status,status,JSON.stringify(data));return {data,cookie:r.headers.get('set-cookie')?.split(';')[0]};}
 const tc=(await api('/auth/register',{body:{role:'teacher',login:'prepared-teacher',name:'Giáo viên',password:'TestOnly123',subjects:['Vật lí']},status:201})).cookie;
 const sc=(await api('/auth/register',{body:{role:'student',login:'prepared-student',name:'HS kiểm thử',password:'TestOnly123',grade:'10'},status:201})).cookie;
 const other=(await api('/auth/register',{body:{role:'teacher',login:'prepared-other',name:'Khác',password:'TestOnly123',subjects:['Toán']},status:201})).cookie;
 const cls=(await api('/teacher/classes',{cookie:tc,body:{name:'Vật lí 10',subject:'Vật lí 10'}})).data.class;await api('/teacher/classes/'+cls.id+'/students',{cookie:tc,body:{login:'prepared-student',name:'HS kiểm thử'}});
 const exam=(await api('/teacher/exams',{cookie:tc,body:{title:fixture.title,subject:'Vật lí 10',duration:45,questions}})).data.exam;await api('/teacher/exams/'+exam.id+'/publish',{cookie:tc,body:{}});
 const assignment=(await api('/teacher/assignments',{cookie:tc,body:{classId:cls.id,examId:exam.id,openAt:new Date(Date.now()-1000).toISOString(),closeAt:new Date(Date.now()+600000).toISOString()}})).data.assignment;
 const endpoint='/teacher/assignments/'+assignment.id+'/solutions',release='/teacher/assignments/'+assignment.id+'/release';
 for(const url of [endpoint+'/template',release]){await api(url,{cookie:sc,status:403});await api(url,{cookie:other,status:404});}
 for(const url of [endpoint+'/preview',endpoint]){await api(url,{cookie:sc,body:{content:'Câu 1. A'},status:403});await api(url,{cookie:other,body:{content:'Câu 1. A'},status:404});}
 const exported=(await api(endpoint+'/template',{cookie:tc})).data.package;assert.equal(exported.items.length,2);assert.ok(!JSON.stringify(exported).includes('HS kiểm thử'));exported.items[0].solution=solution;
 const content=JSON.stringify(exported),preview=(await api(endpoint+'/preview',{cookie:tc,body:{content}})).data;
 assert.equal((await query('SELECT count(*)::int n FROM prepared_solution_sets')).rows[0].n,0);
 await api(endpoint,{cookie:tc,body:{content,previewToken:preview.previewToken},status:400});
 await api(endpoint,{cookie:tc,body:{content,previewToken:'stale',reviewed:true},status:409});
 await api(endpoint,{cookie:tc,body:{content,previewToken:preview.previewToken,reviewed:true}});
 const first=(await api(release,{cookie:tc})).data;assert.equal(first.prepared.ready,1);assert.equal(first.assignment.aiEnabled,false);assert.equal(first.assignment.showExplanations,false);assert.equal(first.job,null);
 const publication={score:false,answers:true,ai:false,explanations:true,timing:'immediate'};
 await api(release,{cookie:tc,body:{...publication,ai:true},status:400});
 await api(release,{cookie:tc,body:publication});
 const id=(await api('/student/start-v9/'+assignment.id,{cookie:sc,body:{}})).data.attemptId;
 const live=(await api('/student/attempt/'+id,{cookie:sc})).data;assert.ok(!JSON.stringify(live).includes('Tính tọa độ'));assert.equal((await api('/student/result/'+id+'/published',{cookie:sc})).data.review,null);
 await api('/student/attempt/'+id+'/save',{cookie:sc,body:{rowVersion:0,answers:{'motion-q':16,'essay-q':'Vận tốc tăng'}}});await api('/student/attempt/'+id+'/submit',{cookie:sc,body:{rowVersion:1}});
 assert.equal((await api('/student/result/'+id+'/published',{cookie:sc})).data.review,null);
 await api('/teacher/attempts/'+id+'/grade-and-release',{cookie:tc,body:{points:2}});
 await query('UPDATE attempts SET question_order=$1 WHERE id=$2',[JSON.stringify(['essay-q','motion-q']),id]);
 const out=(await api('/student/result/'+id+'/published',{cookie:sc})).data;assert.equal(out.result.score,null);assert.equal(out.review.questions[0].aiSolution,null);assert.equal(out.review.questions[1].aiSolution.conclusion,solution.conclusion);assert.equal(out.review.questions[1].aiSolution.source,'prepared');assert.equal(out.review.ai.pending,false);assert.equal(out.review.ai.source,'prepared');
 const text='Câu 2.\nVận tốc tăng nên độ dốc của đồ thị tọa độ tăng theo thời gian.\nKết luận: Tọa độ tăng nhanh dần.',second=(await api(endpoint+'/preview',{cookie:tc,body:{content:text}})).data;
 await api(endpoint,{cookie:tc,body:{content:text,previewToken:second.previewToken,reviewed:true}});
 await api(endpoint,{cookie:tc,body:{content,previewToken:preview.previewToken,reviewed:true},status:409});
 assert.equal((await api(release,{cookie:tc})).data.prepared.ready,2);
 const hidden=(await api('/student/result/'+id+'/published',{cookie:sc})).data;assert.ok(!JSON.stringify(hidden).includes('Tính tọa độ'));assert.ok(!hidden.review.questions[1].aiSolution);
 await api(release,{cookie:tc,body:{...publication,timing:'after_close'}});assert.equal((await api('/student/result/'+id+'/published',{cookie:sc})).data.review,null);
 await query("UPDATE assignments SET close_at=now()-interval '1 second' WHERE id=$1",[assignment.id]);
 assert.equal((await api('/student/result/'+id+'/published',{cookie:sc})).data.review.ai.ready,2);
 await api(release,{cookie:tc,body:{...publication,answers:false,explanations:false}});
 for(const suffix of ['', '/published'])assert.equal((await api('/student/result/'+id+suffix,{cookie:sc})).data.review,null);
 await api('/student/result/'+id+'/review',{cookie:sc,status:403});
 assert.equal(await mod.exports.aiSolutions.runOne(),false);assert.equal(calls,0);assert.equal(Number((await query('SELECT score FROM attempts WHERE id=$1',[id])).rows[0].score),9);
 const row=(await query('SELECT a.*,e.questions FROM assignments a JOIN assignment_exam_versions e ON e.assignment_id=a.id WHERE a.id=$1',[assignment.id])).rows[0];
 const restarted=P.createPreparedService({q:query});assert.equal((await restarted.summary(row)).ready,2);assert.equal((await restarted.summary({...row,questions:[]})).stale,true);
});
